/** AJAX Actions */
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

/** Tree Data API */
export const FETCH_TREE = 'FETCH_TREE';
export const FETCH_TREES = 'FETCH_TREES';
export const FETCH_TREE_SUCCESS = 'FETCH_TREE_SUCCESS';
export const FETCH_TREES_SUCCESS = 'FETCH_TREES_SUCCESS';
export const FETCH_TREES_ERROR = 'FETCH_TREES_ERROR';